# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hangman.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import configparser

from PyQt5.QtWidgets import QFileDialog, QMessageBox, qApp
from PyQt5 import QtCore, QtGui, QtWidgets

from hangman_playground import Ui_Form
from hangman_table import Ui_Table_points
from Setting import Config


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(781, 704)
        MainWindow.setStyleSheet("background-color: rgb(204, 204, 204);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -40, 801, 671))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("1735969.jpg"))
        self.label.setObjectName("label")
        self.but_play = QtWidgets.QPushButton(self.centralwidget)
        self.but_play.setGeometry(QtCore.QRect(580, 610, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Gabriola")
        font.setPointSize(20)
        self.but_play.setFont(font)
        self.but_play.setStyleSheet("background-color: rgb(180, 0, 0);\n"
                                    "color: rgb(203, 203, 203);")
        self.but_play.setIconSize(QtCore.QSize(24, 24))
        self.but_play.setObjectName("but_play")
        self.but_play.clicked.connect(self.show_playground)
        self.but_exit = QtWidgets.QPushButton(self.centralwidget)
        self.but_exit.setGeometry(QtCore.QRect(60, 610, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Gabriola")
        font.setPointSize(20)
        self.but_exit.setFont(font)
        self.but_exit.setStyleSheet("background-color: rgb(0, 0, 0);\n"
                                    "color: rgb(206, 206, 206);")
        self.but_exit.setObjectName("but_exit")
        self.but_exit.clicked.connect(qApp.quit)
        self.input_name = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.input_name.setGeometry(QtCore.QRect(290, 630, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(12)
        self.input_name.setFont(font)
        self.input_name.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.input_name.setObjectName("input_name")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(290, 600, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Gabriola")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.label_2.setObjectName("label_2")
        self.btn_ok = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ok.setGeometry(QtCore.QRect(450, 630, 41, 31))
        self.btn_ok.setStyleSheet("background-color: rgb(203, 203, 203);")
        self.btn_ok.setObjectName("btn_ok")
        self.btn_ok.clicked.connect(self.enter_name)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 781, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.open_file = QtWidgets.QAction(MainWindow)
        self.open_file.setObjectName("open_file")
        self.table = QtWidgets.QAction(MainWindow)
        self.table.setObjectName("table")
        self.game_rules = QtWidgets.QAction(MainWindow)
        self.game_rules.setObjectName("game_rules")
        self.menu.addAction(self.open_file)
        self.menu.addAction(self.table)
        self.menu.addAction(self.game_rules)
        self.menu.addSeparator()
        self.menubar.addAction(self.menu.menuAction())

        self.start_message()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.open_file.triggered.connect(self.choose_file)
        self.table.triggered.connect(self.show_table)
        self.game_rules.triggered.connect(self.show_rules)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.but_play.setText(_translate("MainWindow", "Играть"))
        self.but_exit.setText(_translate("MainWindow", "Выйти из игры"))
        self.label_2.setText(_translate("MainWindow", "Введите имя"))
        self.btn_ok.setText(_translate("MainWindow", "ОК"))
        self.menu.setTitle(_translate("MainWindow", "Меню"))
        self.open_file.setText(_translate("MainWindow", "Выбрать файл для игры"))
        self.table.setText(_translate("MainWindow", "Таблица рейтинга"))
        self.game_rules.setText(_translate("MainWindow", "Правила игры"))

    def start_message(self):
        start = QMessageBox()
        start.setWindowTitle('Вас поймали')
        start.setText(
            'Добро пожаловать в игру "Виселица", перед началом игры не забудьте в меню выбрать текстовый файл для '
            'игры, а также '
            'ввести имя игрока. Приятной вам игры)')
        start.setIcon(QMessageBox.Information)
        start.setStandardButtons(QMessageBox.Ok)
        start.exec_()

    def choose_file(self):
        file = QFileDialog.getOpenFileName()
        directory = Config()
        directory.change_config("settings.ini", "Settings", "directory", str(file[0]))

    def show_table(self):
        self.menu_window = QtWidgets.QWidget()
        self.table_window = Ui_Table_points()
        self.table_window.setupUi(self.menu_window)
        self.menu_window.show()
        self.table_window.table_name()

    def show_rules(self):
        rules = QMessageBox()
        rules.setWindowTitle('Правила игры')
        rules.setText(
            'Виселица - старая добрая игрушка. Загадывается слово, и ты буква за буквой пытаешься его угадать. '
            'На это дается 6 попыток, за каждое угаданное слово даётся 100 очков. '
            'Удачи вам на виселице')
        rules.setIcon(QMessageBox.Information)
        rules.setStandardButtons(QMessageBox.Ok)
        rules.exec_()

    def show_playground(self):
        self.menu_window = QtWidgets.QWidget()
        self.play_window = Ui_Form()
        self.play_window.setupUi(self.menu_window)
        self.menu_window.show()

    def enter_name(self):
        name = str(self.input_name.toPlainText())
        if name == "":
            not_name = QMessageBox()
            not_name.setWindowTitle('Ошибка в имени')
            not_name.setText('Введите имя игрока и нажмите кнопку "Ok"')
            not_name.setIcon(QMessageBox.Warning)
            not_name.setStandardButtons(QMessageBox.Ok)
            not_name.exec_()
        player_name = Config()
        player_name.change_config("settings.ini", "Name_points", "name", name)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
